export const archetypes = [
  { id: 'Black Sacrifice', name: 'Black Sacrifice' },
  { id: 'Blue Terror', name: 'Blue Terror' },
  { id: 'Bogles', name: 'Bogles' },
  { id: 'Burn', name: 'Burn' },
  { id: 'Caw-Gates', name: 'Caw-Gates' },
  { id: 'Cycle Storm', name: 'Cycle Storm' },
  { id: 'Dimir Control', name: 'Dimir Control' },
  { id: 'Dimir Faeries', name: 'Dimir Faeries' },
  { id: 'Dredge', name: 'Dredge' },
  { id: 'Elves', name: 'Elves' },
  { id: 'Familiars', name: 'Familiars' },
  { id: 'Glintblade', name: 'Glintblade' },
  { id: 'Golgari Gardens', name: 'Golgari Gardens' },
  { id: 'Grixis Affinity', name: 'Grixis Affinity' },
  { id: 'Gruul Ponza', name: 'Gruul Ponza' },
  { id: 'Gruul Ramp', name: 'Gruul Ramp' },
  { id: 'High Tide', name: 'High Tide' },
  { id: 'Jund Wildfire', name: 'Jund Wildfire' },
  { id: 'Madness Burn', name: 'Madness Burn' },
  { id: 'Mono Red Madness', name: 'Mono Red Madness' },
  { id: 'Mono Red Rally', name: 'Mono Red Rally' },
  { id: 'Mono-Blue Faeries', name: 'Mono-Blue Faeries' },
  { id: 'Mono-White Aggro', name: 'Mono-White Aggro' },
  { id: 'Mono-White Heroic', name: 'Mono-White Heroic' },
  { id: 'Spy Combo', name: 'Spy Combo' },
  { id: 'Tron', name: 'Tron' },
  { id: 'Unknown', name: 'Unknown' },
  { id: 'Walls Combo', name: 'Walls Combo' },
];
